version: '2'
services:
  rawgithack:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    restart: always
    network_mode: host
    volumes:
      - cache:/var/cache/nginx/rawgithack:rw
      - patrons_cache:/var/cache/nginx/rawgithack_patrons:rw
      - ..:/etc/nginx/rawgithack
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  cache:
  patrons_cache:
